### ISSUE TITLE
Updating underlying packages

### ISSUE THREAD

**Issue by has-n** [MobileFirstLLC/extension-cli#116]
Sorry if I'm missing something obvious here but I'm unable to figure out how to update the underlying packages. 

I installed extension-cli last month and created a project. That was 1.2.0 which used webpack-stream 6.1.2.

I want to update webpack-stream to 7.0.0 but am unable to figure out how to do this. 

Specifically, webpack-stream uses webpack 5 which supports conditional chaining. 

I guess this is quite the conditional chain in itself!

**Comment by nkrusch** [comment]
Hi, I just made a new release. The intent of the cli is to make this process easier, but let me know if I am behind with the dependencies, I will push an update to npm.

**Comment by nkrusch** [comment]
Please try and let me know if that resolves the original issue.

```
npm i extension-cli@1.2.4-beta.0
```

**Comment by nkrusch** [comment]
This is released now, will close.
