### ISSUE TITLE
Copy directories during build

### ISSUE THREAD

**Issue by nkrusch** [MobileFirstLLC/extension-cli#32]
**Describe the bug**
Copy as-is does copy directories.

**Expected behavior**
Make copy support copying of whole directories

**Comment by zicsus** [comment]
https://github.com/MobileFirstLLC/extension-cli/pull/34

**Comment by nkrusch** [comment]
I have merged your PR. Please try 0.11.8-alpha.1 version and see if it resolves the issue.

**Comment by zicsus** [comment]
@nkrusch Thanks! will take look.

**Comment by nkrusch** [comment]
Closing, this is in [v0.11.8](https://github.com/MobileFirstLLC/extension-cli/releases/tag/v0.11.8).
