### ISSUE TITLE
Manifest version for new projects

### ISSUE THREAD

**Issue by nkrusch** [MobileFirstLLC/extension-cli#86]
When creating a new project, currently manifest defaults to v2, which is not recommended for chrome, and FF will move to v3 some day (?), but this will be a _very gradual_ migration overall.

- [ ] change starter manifest to v3 (extension-cli/config/init/manifest.json)

EDIT: this task is to change current starter MV2 to MV3 since it is widely supported. If project owner wants to downgrade it is fairly simple to change the manifest keys locally per project.

**Comment by nicolas377** [comment]
You all should probably set the default to MV3, since nobody outside of Google is really sure of the future of MV2, and its deprecation dates.

**Comment by nkrusch** [comment]
Did you mean set default to MV2?

**Comment by nicolas377** [comment]
All the chromium based browsers support MV3, and all its API's. Firefox plans to release support for MV3 [in early 2022](https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/).

**Comment by nkrusch** [comment]
Ah ok, yes, then it should default to MV3 for sure.
